## Homework
### Migration problem cycle stands
### define a 6*6 matrix such that each column sum is 1
### define another matrix 1*6 with total 50000

In [5]:
import sympy as sp

In [6]:
A = sp.Matrix([[0.3,0.1,0.15,0.2,0.25,0.15],[0.1,0.2,0.15,0.25,0.35,0.05],[0.15,0.05,0.2,0.05,0.1,0.2],[0.1,0.3,0.25,0.1,0.2,0.15],[0.2,0.3,0.1,0.25,0.05,0.2],[0.15,0.05,0.15,0.15,0.05,0.25]])
B = sp.Matrix([10000,4000,6000,7500,7500,15000])

In [7]:
A

Matrix([
[ 0.3,  0.1, 0.15,  0.2, 0.25, 0.15],
[ 0.1,  0.2, 0.15, 0.25, 0.35, 0.05],
[0.15, 0.05,  0.2, 0.05,  0.1,  0.2],
[ 0.1,  0.3, 0.25,  0.1,  0.2, 0.15],
[ 0.2,  0.3,  0.1, 0.25, 0.05,  0.2],
[0.15, 0.05, 0.15, 0.15, 0.05, 0.25]])

In [8]:
B

Matrix([
[10000],
[ 4000],
[ 6000],
[ 7500],
[ 7500],
[15000]])

In [9]:
def problem(n):
    P, D = A.diagonalize()
    D_n = D**n
    A_power_n = P * D_n * P.inv()
    A_power_n*B
    return A_power_n*B

In [10]:
problem(1)

Matrix([
[9925.0],
[7950.0],
[7025.0],
[8200.0],
[9050.0],
[7850.0]])

In [11]:
problem(10)

Matrix([
[9896.92021389917],
[9657.22283499219],
[5756.49549087192],
[9048.37859674897],
[9428.25016449546],
[6212.73269899228]])

In [12]:
problem(100)

Matrix([
[9896.92114531065],
[9657.23238985589],
[5756.48637633299],
[9048.38114916239],
[9428.25535548731],
[6212.72358385075]])

In [13]:
problem(1000)

Matrix([
[9896.92114531065],
[9657.23238985589],
[5756.48637633299],
[9048.38114916239],
[9428.25535548731],
[6212.72358385075]])

In [14]:
problem(1000)

Matrix([
[9896.92114531065],
[9657.23238985589],
[5756.48637633299],
[9048.38114916239],
[9428.25535548731],
[6212.72358385075]])

In [15]:
problem(90)

Matrix([
[9896.92114531065],
[9657.23238985589],
[5756.48637633299],
[9048.38114916239],
[9428.25535548731],
[6212.72358385075]])

In [20]:
import numpy as np


In [21]:
P = np.array([[0.3,0.1,0.15,0.2,0.25,0.15],[0.1,0.2,0.15,0.25,0.35,0.05],[0.15,0.05,0.2,0.05,0.1,0.2],[0.1,0.3,0.25,0.1,0.2,0.15],[0.2,0.3,0.1,0.25,0.05,0.2],[0.15,0.05,0.15,0.15,0.05,0.25]])
X = np.array([10000,4000,6000,7500,7500,15000])

In [26]:
print (np.linalg.matrix_power(P,200)@X)

[9896.92114531 9657.23238986 5756.48637633 9048.38114916 9428.25535549
 6212.72358385]


In [27]:
print (np.linalg.matrix_power(P,20000)@X)

[9896.92114531 9657.23238986 5756.48637633 9048.38114916 9428.25535549
 6212.72358385]


In [29]:
print (np.linalg.matrix_power(P,200))

[[0.19793842 0.19793842 0.19793842 0.19793842 0.19793842 0.19793842]
 [0.19314465 0.19314465 0.19314465 0.19314465 0.19314465 0.19314465]
 [0.11512973 0.11512973 0.11512973 0.11512973 0.11512973 0.11512973]
 [0.18096762 0.18096762 0.18096762 0.18096762 0.18096762 0.18096762]
 [0.18856511 0.18856511 0.18856511 0.18856511 0.18856511 0.18856511]
 [0.12425447 0.12425447 0.12425447 0.12425447 0.12425447 0.12425447]]


In [30]:
print (np.linalg.matrix_power(P,20000))

[[0.19793842 0.19793842 0.19793842 0.19793842 0.19793842 0.19793842]
 [0.19314465 0.19314465 0.19314465 0.19314465 0.19314465 0.19314465]
 [0.11512973 0.11512973 0.11512973 0.11512973 0.11512973 0.11512973]
 [0.18096762 0.18096762 0.18096762 0.18096762 0.18096762 0.18096762]
 [0.18856511 0.18856511 0.18856511 0.18856511 0.18856511 0.18856511]
 [0.12425447 0.12425447 0.12425447 0.12425447 0.12425447 0.12425447]]
